services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "9998:80"
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    restart: always
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ADK_API_URL=${ADK_API_URL}

  agent:
    build:
      context: back-end
      dockerfile: Dockerfile
    restart: always
    command: [adk", "api_server"]
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
